# Generated by Django 5.0.6 on 2024-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='hero_image',
            field=models.ImageField(default='static/images/profile_images/WhatsApp_Image_2022-10-27_at_7.53.50_AM.jpeg', upload_to='static/images/profile_images/bg'),
            preserve_default=False,
        ),
    ]
